- src/Views/Archive.axaml
- src/Views/CherryPick.axaml
- src/Views/CommitBaseInfo.axaml
- src/Views/CreateBranch.axaml
- src/Views/CreateTag.axaml
- src/Views/EditRepositoryNode.axaml
- src/Views/Launcher.axaml
- src/Views/Pull.axaml
- src/Views/Rebase.axaml
- src/Views/Revert.axaml
- Binding with Converter simplification
- Extra curly braces removed
> Syntax Fixes

- src/Commands/AssumeUnchanged.cs
- src/Commands/Blame.cs
- src/Commands/Command.cs
- src/Commands/CompareRevisions.cs
- src/Commands/Diff.cs
- src/Commands/IsBinary.cs
- src/Commands/QueryBranches.cs
- src/Commands/QueryCommitChanges.cs
- src/Commands/QueryFileSize.cs
- src/Commands/QueryLocalChanges.cs
- src/Commands/QueryRemotes.cs
- src/Commands/QueryRevisionObjects.cs
- src/Commands/QueryStagedFileBlobGuid.cs
- src/Commands/QueryStashChanges.cs
- src/Commands/QueryStashes.cs
- src/Commands/QuerySubmodules.cs
- src/Models/DiffResult.cs
- src/Models/Remote.cs
- src/ViewModels/InitGitFlow.cs
RegEx changed to Source Generated to improve perfomance:
- [.NET regular expression source generators](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators)
- [Regular Expression Improvements in .NET 7](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/)
> Source Generated RegEx

- .config/dotnet-tools.json
- .editorconfig
- .gitattributes
- .gitignore
- Directory.Build.props
- SourceGit.sln
- global.json
1. Global.json to control SDK Version [info](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json)
2. Local tools (dotnet-tools.json) to control specials dotnet tools [info](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool)
3. Accelerate Builds for VS [info](https://devblogs.microsoft.com/visualstudio/vs-toolbox-accelerate-your-builds-of-sdk-style-net-projects/)
4. Generic .gitattributes
5. Generic .gitignore with extended definitions
6. Namespaces rules
7. Solution Structure
> DRAFT: Solution Structure Update

- src/SourceGit/Native/OS.cs
So the null check is not needed.
> _backend will never be null

- src/ViewModels/WorkingCopy.cs
- src/Views/WorkingCopy.axaml
feat: shows the number of files in the current list on unstaged and staged lists
Screenshot
> feat: shows the number of files in the current list on unstaged and staged lists

- build/build.linux.sh
Linux archive needs the icon file for create .desktop file
> build: copy .icns file into Linux archive

- src/Converters/BoolConverters.cs
- src/Views/CommitBaseInfo.axaml
> fix: Fixed the issue when the email address is too long and exceeds the scope of the StackPanel

- src/Converters/StringConverters.cs
- src/Resources/Locales/en_US.axaml
- src/Resources/Locales/zh_CN.axaml
- src/Views/Preference.axaml
- src/Views/Preference.axaml.cs
> feat: show tooltip if git version too low

- src/App.axaml.cs
- src/ViewModels/Clone.cs
Allow populating the repository URL from the clipboard if the clipboard contains a valid URL.
> feature: Allow populating the repository URL from the clipboard

- src/ViewModels/Repository.cs
- src/Views/Repository.axaml
- src/Views/Repository.axaml.cs
Double click/tab to open a submodule
> Quick open submodule

- src/App.axaml.cs
Sometimes I encounter unexpected app exits without any logs. Adding a catch for `UnobservedTaskException` may help improve this problem.
> fix: log UnobservedTaskException

- src/Resources/Locales/en_US.axaml
- src/ViewModels/Histories.cs
Added "Copy Info" menu item into history view to copy shot sha and commit subject like
`ab08cde - added some things`
> Add copy info that copies "{Short SHA} - {commit subject}" into clipboard

- README.md
- src/App.axaml
- src/Models/Locales.cs
- src/Resources/Locales/de_DE.axaml
- Adds German translation
- Adds option in Settings modal
- Adds German language option to README
Fixes #305
> Add German translation

- src/SourceGit.csproj
- AvaloniaEdit
- TextMate
- Grammars
> update AvaloniaEdit nuget

- src/ViewModels/WorkingCopy.cs
fix issue like this:
https://github.com/user-attachments/assets/9243b980-8109-4df8-b80e-d032ce3a1149
> fix: clean SelectedStaged after commit

- src/Resources/Locales/de_DE.axaml
As mentioned in the [issue](https://github.com/sourcegit-scm/sourcegit/issues/331) I went through the German translations and found some things which could be improved. I'll add a review to this PR to comment on my suggestions for the translations. I won't add any comments on the simple typos. 
A code review by @warappa would be greatly appreciated. 
Fixes #331
>  Enhance German translation (2)

- src/ViewModels/EditRemote.cs
> fix: remove null-check of sshKey in EditRemote

- src/Resources/Locales/de_DE.axaml
These are (at least should be) all the suggestions from the code review for #349. They will improve the German translation. 
Thanks to @warappa for the review on #349!
> Code review suggestions for German translation

- src/Resources/Locales/pt_BR.axaml
Updated the pt-BR translation as requested in #304
> fix: update pt-BR locale w/ new strings

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/package.yml
- .github/workflows/release.yml
This will fix missing permissions for the OSX application
This also includes a refactoring of the CI to be able to test the package built form pull request and catch this kind of bugs at an early stage
> Fix missing permissions for OSX app

- src/Native/MacOS.cs
> Support iTerm2 in MacOS

- src/Views/Preference.axaml
> ux: Preference fit to content width

- src/Views/CommitRefsPresenter.cs
> enhance: make HEAD commit badge highlight

- src/Commands/Statistics.cs
see https://git-scm.com/docs/gitmailmap
> Respect .mailmap files in statistics

- src/Resources/Locales/fr_FR.axaml
Commit made on behalf of @thomaschampagne.
Took reviewed strings defined as legit in PR #424.
> Add legit enhancements to French locale

- src/Views/Preference.axaml
20,000 commits is too stressful for low-end configurations (such as my i3-7350k), and it is easy to get stuck.
> enhance: reduce Minimum of History Commits setting

- src/Commands/Command.cs
> enhance: append to PATH on MacOS instead of overriding it

- src/Resources/Locales/de_DE.axaml
Added the new german translations again.
`Text.Diff.IgnoreWhitespace` is just the same as `Text.Apply.IgnoreWS`
For `Text.Discard.IncludeIgnored` I went with a similar translation as for `Text.WorkingCopy.IncludeUntracked`
> Add DE keys for new features

- src/Commands/QueryCommits.cs
- src/Commands/QueryCommitsWithFullMessage.cs
> fix: Display all parents even if there are more then 2

- src/Models/CommitTemplate.cs
- src/ViewModels/WorkingCopy.cs
- src/Views/RepositoryConfigure.axaml
This adds `${branch_name}` as an option for commit templates
> feature: add `${branch_name}` option to commit templates

- src/Resources/Locales/de_DE.axaml
- Fix one misspelling where a "c" was missing before a "c" in the work Auschecken
- Add missing DE translations for new feature items
> localization: Add missing DE keys, fix misspelling

- .editorconfig
- .github/scripts/localization-check.js
- .github/workflows/localization-check.yml
- .gitignore
- README.md
- SourceGit.sln
- TRANSLATION.md
Add localization check CI and translations missing keys in documents. Using `nodejs` but not `python` is my personal preference. Maybe I can do this with `.Net` unit tests, but I'm not very familiar with how to write this in `.Net`.
> ci: add Localization Check CI

- src/App.axaml
- src/Models/Locales.cs
- src/Resources/Locales/es_ES.axaml
localization: added es_ES.axaml
> localization: added es_ES.axaml

- src/ViewModels/Pull.cs
- src/Views/WorkingCopy.axaml
1. fix bug that stuck auto fetch when pull failed.
2. make stage area resizeable.
> fix bug that stuck auto fetch when pull failed & make stage area resizeable

- src/Resources/Locales/es_ES.axaml
Adds missing translations keys in spanish
> Add missing translations in spanish

- src/Resources/Locales/es_ES.axaml
Add missing translation in spanish
> Update spanish translation

- src/Resources/Locales/de_DE.axaml
Added missing keys.
The changes are mostly code review suggestions from #664 @Stern1710 I hope you're ok with me adding my own suggestions 😅 
`ClearAllCommitsFilter` is not about deleting ("Löschen") therefore I changed that.
Not fully satisfied with `FilterCommits.Include` for the german but also english translation, however I couldn't come up with something better.
> Add and improve de_DE keys

- README.md
- TRANSLATION.md
- src/Resources/Locales/pt_BR.axaml
updated the pt-BR strings, and rearranged the order so we can use the diff tool to find the missing strings easier
> update pt-BR strings

- src/Models/Remote.cs
> Better https regex for the repo url

- src/Resources/Locales/de_DE.axaml
Regarding `Text.SHALinkCM.NavigateTo` I felt like "Go to" was a bit imprecise so I went for a translation more similar to "Go to Commit".
> Add missing de_DE keys

- TRANSLATION.md
- src/App.axaml
- src/Models/Locales.cs
- src/Resources/Locales/it_IT.axaml
> Italian translation

- src/Resources/Locales/en_US.axaml
> Fix grammar in tip

- src/Resources/Locales/en_US.axaml
- src/Resources/Locales/ru_RU.axaml
After spending some time in work with the SourceGit I've found that some messages need fix.
> Fix some more messages in russian and english

- src/Resources/Locales/ru_RU.axaml
> localization: update

- src/Resources/Locales/ru_RU.axaml
> update translation russian

- src/Resources/Locales/ru_RU.axaml
> update russian translate

- src/Resources/Locales/fr_FR.axaml
- "Checkout" translates to "Récupérer". Updating lines that match.
- "Push" translates to "Pousser". Updating lines that match.
- Staged translates to "Présent dans l'index" but it is too long to I go simply for "Indexé".
- Translating a few extra lines.
- Some of the terms mentioned above remain untranslated because it is not appropriate provided their respective context.
> style(locale): Translate French locale further

- src/Models/TemplateEngine.cs
> Fix `_` is not parsed in template variable name

- src/Commands/Stash.cs
> fix: add `--include-untracked` to `stash push` for specific changes

- src/Models/Watcher.cs
> enhance: async refresh operations in Watcher

- src/Resources/Locales/de_DE.axaml
I did not translate `Stash`  and `SignOff` as I think those two are very specific git comments, where as the german translations would be more confusing.
> added missing german translations

- src/Resources/Locales/de_DE.axaml
"Branch" will not be translated for better understanding.
> add german translations

- SourceGit.sln
- build/resources/deb/DEBIAN/preinst
- build/resources/deb/DEBIAN/prerm
> build: Add pre-install and pre-removal scripts for DEBIAN package

- build/scripts/package.windows.sh
my test in github actions is still running, this should fix the issue.
> ci(windows): maintain SourceGit folder structure

- src/Resources/Locales/de_DE.axaml
- src/Resources/Locales/en_US.axaml
- src/Resources/Locales/es_ES.axaml
- src/Resources/Locales/fr_FR.axaml
- src/Resources/Locales/it_IT.axaml
- src/Resources/Locales/pt_BR.axaml
- src/Resources/Locales/ru_RU.axaml
- src/Resources/Locales/zh_CN.axaml
- src/Resources/Locales/zh_TW.axaml
- src/Views/CommitTimeTextBlock.cs
> feat: add translation for "1 hour ago" in multiple languages

- src/App.axaml.cs
Restore the process removed by 9560496c7bf9cec50f98f19d8b37dbe98d71fcf9
> fix: improve font family name handling by collapsing multiple spaces

- src/Models/AvatarManager.cs
test code :
```chsarp
[Params("andya@microsoft.com", "noreply@github.com")]
public string Emails { get; set; }
[Params(128, 512)]
public int Times { get; set; }
[Benchmark(Baseline = true)]
public void GetEmailHashTest()
{
int count = 0;
for (int i = 0; i < Times; i++)
{
var result = GetEmailHash(Emails);
if (!string.IsNullOrWhiteSpace(result))
{
count += 1;
}
}
}
[Benchmark]
public void GetEmailHashPrefTest()
{
int count = 0;
for (int i = 0; i < Times; i++)
{
var result = GetEmailHashPref(Emails);
if (!string.IsNullOrWhiteSpace(result))
{
count += 1;
}
}
}
public string GetEmailHash(string email)
{
var lowered = Emails.ToLower(CultureInfo.CurrentCulture).Trim();
var hash = MD5.Create().ComputeHash(Encoding.Default.GetBytes(lowered));
var builder = new StringBuilder();
foreach (var c in …
```
> get email hash code opimization

- src/Resources/Locales/fr_FR.axaml
Took a little time to continue with French translation.
Is this correct in English version ?
`<x:String x:Key="Text.SetUpstream" xml:space="preserve">Set Tracking Branch</x:String>`
Key tells upstream but value tells tracking branch. I followed the value.
> Locale fr 2504

- src/Resources/Locales/es_ES.axaml
add missing translations
modify instances of `stagear` with `hacer stage`
> localization: update spanish translations

- src/Views/RepositoryConfigure.axaml.cs
Resolves #1268 
I had to check this out. :)
> close Repository Configuration on Esc

- src/Commands/QueryLocalChanges.cs
fix sourcegit-scm/sourcegit#1326
> enhance: Show the stderr content from `QueryLocalChanges`

- src/ViewModels/Histories.cs
perf: minimize temporary strings for better performance
> minimize temporary strings for better performance

- src/ViewModels/WorkingCopy.cs
Sometimes I'd like to open (un)staged changes in my external diff tool.
> enhance: diff with merger option on local changes

- src/Resources/Locales/en_US.axaml
Inconsistent use of "Pages" and "Tabs" terminology in the UX. As far as I can tell these two things are equivalent. Tabs appear to be more common so I switched to that everywhere.
> ux: inconsistent tabs/pages terminology

- src/Views/CommandLogTime.cs
Minor tweak to the command log duration format, another good use for `G3`!
> enhance: more readable command log duration

- src/Resources/Locales/es_ES.axaml
> localization: update Spanish translation
