sourcegit-scm/sourcegit

src/SourceGit/ViewModels/RepositoryConfigure.cs

Fix spelling errors in configuration keys
Before this PR:
- An exception is occured when the user open the repository settings.
After this PR:
- The exception is fixed.

Fix spelling errors in configuration keys

---

src/Native/Windows.cs

Fixed the problem that the AvaloniaRider plugin on Windows cannot display the live preview for Avalonia XAML

fix: Fixed the NullReferenceException in AvaloniaRider plugin on Windows

---

src/Native/Windows.cs

Before this PR:
The Windows Terminal always use the default startup directory of the default profile.
After this PR:
The Windows Terminal will use the repository directory as the startup directory.

Fix windows terminal startup directory

---

.github/workflows/ci.yml

By default the compiled program will not run on macOS or Linux and the user must use `chmod` to enable the ability to execute.
By adding another step in the jobs for macOS and Linux the artifact will now run when the user downloads. 
> c7784b0

Added ability to run program by default for macOS and Linux

---

.github/workflows/ci.yml

In order to stop the permissions from being reset you have to put the Linux and macOS files in a tarball before uploading the artifact. They are now `tar.zip` archives that retain the executable flag.
_Originally suggested by @gadfly3173 in https://github.com/sourcegit-scm/sourcegit/issues/107#issuecomment-2095039775_

Fixed Linux and macOS not being executable

---

src/Resources/Styles.axaml
src/Views/Launcher.axaml
src/Views/Launcher.axaml.cs

Commit `e5516b5` is used to fix the rebound problem that occurs when scrolling on mice such as Logitech G903 that support left and right scrolling.

Enhance launcherTabsScroller scroll behavior

---

src/Views/Launcher.axaml.cs

Depending on the implementation of the desktop environment, the BeginMoveDrag method may cause WindowState assign to not take effect or the window size to flicker.

fix: DoubleTapped on launcherTabsScroller not triggered correctly

---

SourceGit.sln
src/Models/Remote.cs
tests/SourceGit.UnitTests/RemoteTests.cs
tests/SourceGit.UnitTests/SourceGit.UnitTests.csproj

Currently, it is not possible to clone repositories hosted in **Azure DevOps / Azure Repos**.
This is due to **the way the URL is built**, both for HTTPS and SSH. Differently from mostly Git providers, the repository lacks a `.git` suffix.
- Changed the RegEx to make the `.git` suffix optional.
- Added Unit Tests to ensure GitHub and Azure Repos URLs are considered valid.
https://learn.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio-2022
https://stackoverflow.com/questions/52355510/what-is-the-url-for-a-new-azure-git-repos-if-the-project-is-in-visual-studio-on

Allowing Azure DevOps / Azure Repos URLs

---

src/ViewModels/Repository.cs

When pushing without a branch, it seems that it did not return correctly.

Fix the crash caused by pushing without a branch

---

src/Models/GPGFormat.cs
src/Resources/Locales/en_US.axaml
src/Resources/Locales/zh_CN.axaml
src/ViewModels/RepositoryConfigure.cs
src/Views/Preference.axaml
src/Views/Preference.axaml.cs
src/Views/RepositoryConfigure.axaml

This commit is signed with ssh on Windows 10. This PR didn't add X.509 because I cannot test that format.
SSH commit sign default use `ssh-keygen` and use specific public key file, so I didn't add the config of `gpg.ssh.program`

feat: add gpg format switcher (#154)

---

src/ViewModels/AddRemote.cs

1. There is no need to force specify sshKey when adding a remote repository.
2. Setting sshKey after fetch does not seem to have the expected effect. Because `new Commands.Fetch` has already read the corresponding configuration `$"remote.{remote}.sshkey"`

fix: remove null-check of sshKey in AddRemote and change command execution order

---

README.md
src/App.axaml
src/Resources/Locales/zh_TW.axaml

This Pull Request adds support for Traditional Chinese (zh_TW) internationalization (i18n) to the project. It includes translations for user-facing text and integrates with the existing i18n framework.
- Added zh_TW translation files
- Updated i18n configuration to include zh_TW support
- Translated all user interface text to Traditional Chinese
I hope this addition will allow Traditional Chinese users to use the software in their preferred language, making it more accessible and user-friendly.

feat: add support for Traditional Chinese (zh_TW) i18n

---

src/Resources/Locales/en_US.axaml

- Menu entries that require additional input end with ellipsis.
- No blank space before ellipsis or colon.
- A few minor tweaks e.g. to unify the style of adjacent choices.
While I'm not a native English speaker, I'd like to suggest some changes to make the English translation better follow en-US conventions as well as the recommended use of ellipses in most interface guidelines to indicate further dialog or such, as [Apple puts it](https://developer.apple.com/design/human-interface-guidelines/menus):
> Append an ellipsis to a menu item’s label when the action requires more information before it can complete.

Tweak English translations.

---

src/Views/Launcher.axaml.cs

Close any tab with mouse middle click button

Middle Button Close Tab

---

src/Views/Repository.axaml

This PR fixes the issue where the radio button does not highlight when switching using the Ctrl+F shortcut.

fix: SearchFilter radio button checked status

---

.github/workflows/ci.yml

Downgrade MacOS for #245
Downgrade Linux for #267
Downgrade Windows because Windows 2019 runner runs faster than 2022

ci: downgrade ci system

---

src/Models/RepositorySettings.cs
src/Resources/Locales/en_US.axaml
src/ViewModels/Pull.cs
src/Views/Pull.axaml

By default Pull doesn't fetch all branches.
Add fetch (without Prune) all branches on pull option to Pull window (acts like fetch+pull)
Reduces one click in many workflows and optional.

Add fetch all branches on pull option (acts like fetch+pull)

---

src/Views/Launcher.axaml

From 1280x720 to 1024x600, to fit window in top-half / top-third of portrait 1920x1080 monitor:
Tested on Windows.
Setting font size to 11.0 mitigates issues with text being cut off due to reduced width.
```
x=1080     
+------------+
| SourceGit  |  y=640
|            |      \
+------------+        \
|File Browser|  y=640  } y=1920
|            |        /
+------------+      /
| Web Browser|  y=640
|            |
+------------+

Reduce Minimum window size

---

.github/workflows/ci.yml

Add CI build step for Linux arm64.

enhance: add CI for arm64

---

build/resources/_common/applications/sourcegit.desktop

This will automatically add sourcegit to right-click menu for folders in file managers.

Register to directory MimeType to open folders in unix systems

---

.github/workflows/ci.yml
.github/workflows/package.yml
.github/workflows/release.yml
build/build.linux.sh
build/ci/package.linux.sh
build/ci/package.osx-app.sh
build/ci/package.windows-portable.sh
build/resources/appimage/sourcegit.appdata.xml
build/resources/deb/DEBIAN/control
build/resources/deb/DEBIAN/postinst
build/resources/deb/DEBIAN/postrm
build/resources/rpm/SPECS/build.spec

This will automate Source Git binary releases.
When the tag is pushed, a new release is created with all built packages attached.
Some minor changes include:
* Embed symbolic links in Linux packages
* Fix AppImage metadata warnings
* Refactor ci.yml to use matrix
One of the considerations is how to handle version. Currently it gets the version from the tag (`v1.0.0` => `1.0.0`), but it could be changed to use the VERSION file from the project root.
By default, the release uses the message from the annotated tag or the latest commit message if the tag is liteweight, but this could be edited later.

Automatic CI releases

---

src/Resources/Locales/de_DE.axaml

I saw the new key was added, so I added a German translation.
For the translation I also considered going with "AppData" however this is really only used on Windows (AFAIK). Therefore a translated version seems more universal.

Add German translation 'open app data dir'

---

src/Resources/Locales/de_DE.axaml

I added the new keys for Commit-Template and Reset to Revision for the German translation. 
Template could have also been translated to "Vorlage" but in my experience especially in technical environments "Template" is actually more commonly used. (+ also accepted by [Duden](https://www.duden.de/rechtschreibung/Template))

New keys for german translation

---

src/Resources/Styles.axaml

This pull request fixes the issue with the foreground color in the tooltip for the primary button. The problem was caused by an incorrect selector, which resulted in the tooltip text being displayed in the wrong color.
- ux: foreground for primary button https://github.com/sourcegit-scm/sourcegit/commit/45b93a117e0add3131d5aadd986d434b06275156)
Before:
After:
<br>
I think this issue can be resolved simply by using the child combinator `>`. However, because I'm not familiar with Avalonia UI, I hope this solution does not introduce any unintended side effects.

Fix foreground color in tooltip on primary button

---

src/Views/Repository.axaml.cs

Keep the same implementation as `CommitRefsPresenter` to avoid displaying the number of the previous `DataContext`

fix: invalidate counter visual (#338)

---

src/Native/Windows.cs

This pull request addresses a security issue where an executable file with the same name as a directory could be executed instead of opening the directory.
In scenarios where a directory and an executable file share the same name and are located in the same directory, the existing implementation could mistakenly execute the file instead of opening the intended directory. For example:
```
.
├── danger/
│   ├── .git/
│   └── ...
└── danger.exe
```
When attempting to open the `danger` directory, the program might execute `danger.exe` (calculator in the following demo) instead, which poses a security risk.
https://github.com/user-attachments/assets/303690fd-78b1-4d92-a7db-c419138c427c
To prevent this, I modified the code to ensure that when a directory is intended to be opened, a directory …

Prevent executing an executable file with the same name as the directory

---

src/App.axaml
src/Models/Locales.cs
src/Resources/Locales/fr_FR.axaml

Initial batch to the French translation.
Items translated
- Repo tree

style(locale): Translate to French  Batch 1

---

src/Resources/Locales/zh_TW.axaml

This PR updates the Traditional Chinese translation. The terminology used in Git does not have a standardized translation in Traditional Chinese, and we often use the English terms instead. The translations in projects like Visual Studio, Visual Studio Code, and [git l10n](https://github.com/git/git/tree/master/po) vary slightly. Therefore, this PR attempts to standardize the following terms. For major buttons or options, the original English terms are kept in parentheses after the translation to avoid confusion.
This PR also adds spaces between the Traditional Chinese and English text in the translation and changes some punctuation marks to half-width. This follows the standards from the [Microsoft Chinese (Traditional) Localization Style …

Update Traditional Chinese translation

---

src/Resources/Locales/de_DE.axaml

In 184c89e the key `Text.Squash` was updated for all languages but for the German translation the key `Text.CommitCM.Squash`  was edited. I changed this to comply with the other translations.
Other than that I added translations for the recently added keys.
- `Text.CopyAllText` could have also been translated with "Gesamten Text kopieren" but I liked the idea of the two context menu options "Kopieren" and "Kopiere gesamten Text" both starting with the same word
- `Text.CommitCM.SquashSinceThis` since we used "Vorgänger" instead of "Eltern" to translate "Parent [commit]" I went for "Nachfolger" instead of "Kind" to translate "Child [commit]". Not super happy with the translation but this can always be improved later

Fix and add DE localization keys

---

src/Native/Linux.cs

This adds support for opening a repository with [foot](https://codeberg.org/dnkl/foot), a terminal emulator for Wayland.

Add support for foot

---

src/Views/WorkingCopy.axaml.cs

This is probably a rather subjective change (and more of a proposal). Feel free to reject it if this does not make sense to you.
It's just that using the Enter key to stage/unstage changes feels more intuitive to me (or I'm just used to it).

Add Enter as keybinding for staging/unstaging

---

src/Commands/Checkout.cs
src/ViewModels/CommitDetail.cs

* support reset to parent revision for Added files too
* support reset to parent revision in Files tab
* support reset to parent revision in Changes - now supports Renamings too
now it behaves more like git-extensions

Reset file to parent revision - improvements

---

src/Resources/Styles.axaml
src/Resources/Themes.axaml
src/Views/About.axaml
src/Views/Askpass.axaml
src/Views/AssumeUnchangedManager.axaml
src/Views/CaptionButtonsMacOS.axaml
src/Views/ConfirmRestart.axaml
src/Views/Hotkeys.axaml
src/Views/InteractiveRebase.axaml
src/Views/LFSLocks.axaml
src/Views/Preference.axaml
src/Views/RepositoryConfigure.axaml
src/Views/SelfUpdate.axaml
src/Views/StandaloneCommitMessageEditor.axaml
src/Views/Statistics.axaml

This pull request updates the colors of the macOS window control buttons (Close, Minimize, Maximize) in SourceGit to better match the native appearance.
The colors were obtained by unpacking `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car` and `DarkAqua.car` using [ThemeEngine](https://github.com/jslegendre/ThemeEngine). The colors were then measured using Digital Color Meter. Due to the pixelated nature of the images, there may be slight inaccuracies.
Note: The button border remains set to `<Setter Property="Stroke" Value="#40000000"/>` due to the difficulty in measuring the border thickness, which is very small, and I'm not sure starting from which version of macOS the maximize button's direction was rotated 90 degrees, so I didn't change it.
The …

Improve macOS window control button colors for native appearance

---

src/Resources/Locales/fr_FR.axaml

A second batch of translation for French locale.
The translation should be roughly 2/3 to completion.
Bellow is a non exhaustive list of changes.
Diff.SyntaxHighlight
RevealFile
Revert
Reword
Running
Save
Stash
URL
UpdateSubmodules
Warn
WorkingCopy
Worktree
Some extra sentences
Include small fixes for
CodeEditor : missing accent
Include a fix mentioned in the previous PR #405 but not merged. (non -> nom for name in a string)

style(locale): Translate to French Batch 2

---

src/Native/MacOS.cs

This pull request refactors the method for opening the terminal on macOS by removing the use of temporary AppleScript files. The previous implementation involved generating, executing, and then deleting a temporary AppleScript file. This has been replaced with a more efficient and cleaner approach using the `open -a {terminal} "{dir}"` command to directly launch the desired terminal and open the target directory.
- Using `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` instead of `~` because there is no tilde expansion
- Using `\"{dir}\"`, so the line `dir = dir.Replace(" ", "\\ ");` is removed.

refactor: terminal launch on macOS without temporary AppleScript

---

src/Resources/Locales/de_DE.axaml

I added German translations for the recently added keys.
- "Workspace" could also not be translated however I felt like "Arbeitsplatz" is common enough to use that as a translation
- `Text.Repository.Filter` this was changed in b1457fe, for the German plural of "Submodules" we use "Submodule" 😅 
- `Text.ScanRepositories.RootDir` could also be translated with "Stammverzeichnis" or similar, but I went with "Hauptverzeichnis"
Since I messed up three commit hashes in the commit message here the correct ones in order as they are in the message:
0d676fa3fbf5a597c2451bdc6d00a4780e127417
dffd9d76760246e9eb162d9ad1fa938928f5988c
b1457fe39d7dd777d23843784abe9b8d0fd9d965

Add DE keys for new features

---

src/SourceGit.csproj

This will introduce `SourceGitNoAot` variable, which can be set to `true` to disable native AOT deployment.
While AOT could improve application's speed, bundling the dotnet runtime will also increase its size.
The change is useful for Flatpak with the dotnet runtime included, or for a Linux package that will depend on the `dotnet-runtime` package. This is the more idiomatic way for Linux, and will also minimize the amount of disk space used if the system already has the dotnet runtime installed.
This variable is intended to be used by package maintainers, current Linux CI builds should be left as they are.

Allow to disable native AOT deployment

---

src/Resources/Locales/zh_TW.axaml

Made slight adjustments to the Traditional Chinese translations for the strings added over the past two weeks.
> [!NOTE]
> I would include the following tables in each PR updating the Traditional Chinese translation, so that future contributors to the Traditional Chinese translation could use it as a reference or make corrections.
| Original        | Translation     |
| ----------- | -------- |
| Fetch       | 提取     |
| Pull        | 拉取     |
| Push        | 推送     |
| Rebase      | 重定基底 |
| Cherry-pick | 揀選     |
| Checkout    | 簽出     |
| Amend     | 修補    |
| Blame       | 逐行溯源 |
| Archive     | 封存     |
| Patch       | 修補檔   |
| Stash       | 擱置變更 |
| Track       | 追蹤     |
| Local       | 本機     |
| Repository  | 存放庫   |
| Sign         | 簽章 |
| Discard | 捨棄 |
| Terminal | 終端機 |
| …

localization: update zh_TW.axaml

---

src/Resources/Locales/de_DE.axaml

Added the German translations again.
- Could have left "API Key" since this term is quite common but "Schlüssel" is the actual translation. Works either way

Add DE keys for new OpenAI commit message generation

---

src/Models/ShellOrTerminal.cs
src/Native/Linux.cs
src/Native/OS.cs
src/Native/Windows.cs
src/ViewModels/Preference.cs

* Fix crash on Welcome screen
* Allow custom terminal and non-absolute executable names for terminals (useful when setting a custom terminal)
* Catch errors thrown by `Process.Start` when terminal configuration is invalid on Linux

Few terminal fixes

---

build/scripts/package.linux.sh
build/scripts/package.osx-app.sh
build/scripts/package.windows-portable.sh

* call bash through env progrem
* add more strict defaults
* [ -> [[

build: minor tweaks

---

src/ViewModels/LFSLocks.cs
src/Views/LFSLocks.axaml

I've been adding this checkbox on the LFSLocks window so that only my locks are shown. I'm working on Unreal Engine and sometimes people in my team have dozens of locks due to how World Partition works.
Thanks for reviewing it!

Show only my locks

---

src/Resources/Locales/de_DE.axaml

I found ten localization strings for the German translation to be missing in the current version of the develop branch. I placed the translation into `de_DE.axaml`. To find the missing strings, I wrote a little python script, which I can happily share upon request.

localization: add missing german text entries

---

src/Views/ContextMenuExtension.cs

Sometimes the context menu may be set to `null` before opening. For example, the `Avalonia` repository has many branches. If you right-click multiple times before the context menu of the branch is opened, NRE will appear.

fix: avoid NRE in ContextMenuExtension

---

src/Resources/Locales/de_DE.axaml

Added the new german translations again. A couple difficult ones this time.
`Text.About.Chart` german transaltion for "to render" is actually rendern https://www.duden.de/konjugation/rendern
`Text.CherryPickMainline` the word "Mainline" was unfamiliar to me but seems to be translated with "Hauptlinie"
Both `Text.Stash.. ...` use staged or unstaged as a past tense. Since we went with stage/unstage in german it's quite difficult to translate this grammatically correct.
`Text.Histories.Header.AuthorTime` not quite fond of this but should be understandable

 Add DE keys for new features (stash, author time, chart and cherry-pick)

---

src/Views/Histories.axaml.cs

Update regex to handle conventional commits with breaking changes (!). [doc](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with--to-draw-attention-to-breaking-change)

fix(histories): handle commits with breaking changes

---

src/Commands/GenerateCommitMessage.cs
src/Models/OpenAI.cs
src/Resources/Locales/en_US.axaml
src/SourceGit.csproj
src/ViewModels/Preference.cs
src/Views/Preference.axaml

- Refactor the commit message generation process to utilize default prompts and enhance clarity while eliminating redundancy.
- Added new properties for subject and summary prompts, while improving cancellation support in async task handling.
- feat: add AI prompts for commit message generation.
- Updated the formatting of the package reference for consistency in the project file.
- Add properties for managing OpenAI subject and summary prompts in the Preference view model.
- Refactor layout and add new input fields for AI subject and summary prompts in the preferences view.

feat: improve commit message generation with AI prompts

---

build/resources/rpm/SPECS/build.spec

While most RPM based distributions use `libSM` as a name for this library OpenSUSE uses `libSM6`.
This leads to unfulfilled dependencies when the RPM package is installed on OpenSUSE `Tumbleweed` for example.
I think it is save to require either `libSM` or `libSM6`, because it is very unlikely a distribution would package the library under both names at the same time. And even if they did the package manager would be responsible to resolve this gracefully.

fix: Make RPM builds compatible with OpenSUSE

---

build/resources/rpm/SPECS/build.spec

Similar to #622 this allows an alternative name for `libX11`, some distributions use `libX11-6`.
I did not notice it because [dpkg.org](https://pkgs.org/download/libx11-6) does not show this correctly.
Sorry for the noise.

fix: Make RPM builds compatible with OpenSUSE (libX11)

---

README.md
src/Models/ExternalTool.cs
src/Native/Windows.cs

This allows using Visual Studio as an external tool for opening the repo in.
Current limitations:
* Visual Studio for Mac is not supported.
* It only relies on registry for Visual Studio location (reportedly Visual Studio can be installed without modifying the registry;  other discovery mechanisms may be used).
* SourceGit tries to open the whole repo as a directory.  From my experience,  when you actually need Visual Studio  (as opposed to Visual Studio Code),  you normally want to open a solution file instead.  One may expect a prompt asking how to open a project and allowing to select a solution file interactively.  Instead, the implementation tries to locate a solution file and to open it directly,  falling back to repo directory only in case of failure.
The solution finding bit is …

feature: add support for Visual Studio as external tool

---

src/Resources/Locales/en_US.axaml
src/ViewModels/Histories.cs
src/Views/Histories.axaml.cs
src/Views/Hotkeys.axaml
src/Views/RepositoryToolbar.axaml

Nothing big, just adding keyboard shortcuts for:
- **Pull** (starts directly)
- **Push** (starts directly)
- **Create Branch** (based on selected commit)
Those are some of the operations I do most often, it's nice to have shortcuts. I also added those to the `Hotkeys` window.
For creating branch, I didn't use the `HotKey=""` property of Avalonia XML, as I needed the selected commit. I implemented it on the already existing `OnCommitListKeyDown` event.
Not sure how to handle localization, I've only added the new strings to `en_US`.

Adding hotkeys for creating branch, pushing and pulling

---

src/Resources/Locales/pt_BR.axaml

Just adding some missing **pt_BR** translation keys, as this is my mother language.
This change makes the file fully in sync with the **en_US** localization file.
A comment was also added aiming to bring standardization to the terms, feel free to remove it.

Adding missing pt_BR translation keys

---

src/Resources/Locales/de_DE.axaml
src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/ViewModels/Histories.cs

Adds "Merge {tag} into {branch}" menu item to tag menu in histories.
The rest is handled by already existing merge code.

Allow merging tags into branches

---

src/ViewModels/CommitDetail.cs

* Detect gitlab urls more aggressively - it is common for private Gitlab instances to be served on urls like "gitlab.mycompany.tld."
* Add first 2 components of the path to the menu label so that multiple repos on the same forge could be disambiguated.
* Allow links to codeberg, gitea and sourcehut.

Several commit links improvements

---

.editorconfig
.gitattributes
build/resources/rpm/SPECS/build.spec
build/scripts/package.linux.sh
build/scripts/package.osx-app.sh
build/scripts/package.windows-portable.sh

Refactor rpm's `Requires:` to depend on SO instead of package
Add `*.spec` and `control` to `.gitattributes` and `.editorconfig` (without it vscode will change EOL to CRLF every time file is touched, a bit inconvenient when testing locally)
Remove redundant `VERSION` and `RUNTIME` variable checks in CI build scripts as `set -u` was introduced in #498
Tested with Fedora 41 (x86_64 and arm64), openSUSE 15.6 (x86_64 and arm64)
Closes #686

enhance: depend on SO in rpm package 

---

.github/workflows/package.yml
build/resources/_common/applications/sourcegit.desktop

SourceGit is misspelled in the `.desktop` file, and this inconsistent spelling is really annoying when you use application starters like KRunner or dmenu :grin:

fix: SourceGit misspelled as "Source Git"

---

src/Commands/Branch.cs
src/ViewModels/DeleteBranch.cs

- Allow users to remove local remote-tracking branches without remotes (ie. remote was removed on merge request).
**Displayed error**
- Included 'DeleteRemoteTracking' and 'HasRemote' util methods to handle this case.
- We have local and remote-tracking but not a remote branch. We need to remove both or only the tracking based on the checkbox and on the 'hasRemote' condition

feat: delete orphan remote tracking branches

---

src/ViewModels/CommitDetail.cs
src/ViewModels/FileHistories.cs

Currently when the file history is requested,  `git log` runs against the current branch.  Thus if file history is requested for a file from a commit from another visible branch,  the selected commit does not show up in the history.  When the file was added in another branch and was not yet seen in the current branch,  the history view is just empty.
This PR makes the log run against the selected commit,  which makes most sense to me.
Another approach would probably be to find a first parent reference containing current commit and run log against that,  though to me it would be a bit counter-intuitive.

File histories from commit view

---

src/Models/ExternalMerger.cs

The WinMerge preset in the application opens WinMerge in a 3-way merge configuration with theirs version on the left, ours in the middle and raw conflict file on the right:
This seems to be aligned with the advice on the internet,  but provides suboptimal user experience.  The fact that WinMerge doesn't have keyboard shortcuts to operate on the middle pane doesn't help either.
Winmerge supports opening conflict files directly,  and for them it creates a 2 pane UI with theirs version on the left and ours on the right:
Ours is what is eventually saved when the conflict is resolved.
To me the latter appears to be much more useful,  _though I can see how someone may want to keep both ours and theirs in their view for the whole conflict resolution session_.

Switch WinMerge from 3-way merge to 2-way merge

---

src/Models/ResetMode.cs
src/Views/Reset.axaml
src/Views/Reset.axaml.cs

Hotkeys in order to fast reset a branch:

Reset Mode Hotkey

---

src/Commands/Statistics.cs
src/Models/Statistics.cs

* Use global commit limit instead of hardcoded 40000 commits.
* Adjust the first day of the week for this week stats according to the current culture.

Slightly improve statistics

---

src/Models/CommitTemplate.cs
src/Models/TemplateEngine.cs

This replaces the regex-based approach to templates with a simple non-failing and forgiving parser.
Now there are 3 types of variables:
* Regular variable, it just expands to its value, e.g. `${FILES}` (`BRANCH`, `FILES_COUNT`, `FILES` are supported)
* Sliced variable, it expands to special sliced value limited by `N`, e.g. `${FILES:N}` (currently only `FILES` is supported)
* Regex variable, same as regular variable, but before expanding it replaces `regex` with `replacement`, e.g. `${BRANCH/regex/replacement}`. Supports all variables that regular variables support. No newlines allowed inside `regex` and `replacement` because that's error prone. Capture groups (`$1`, `$2`, ...) are supported, as expanding directly uses `Regex.Replace(String, String)`.
To escape variables within text, use …

enhance: introduce template engine for commit templates

---

src/Commands/QueryCommitChildren.cs
src/Resources/Locales/en_US.axaml
src/Resources/Locales/fr_FR.axaml
src/ViewModels/CommitDetail.cs
src/ViewModels/Preference.cs
src/Views/CommitBaseInfo.axaml
src/Views/CommitBaseInfo.axaml.cs
src/Views/CommitDetail.axaml
src/Views/Preference.axaml

This is an updated version of a previously merged and reverted #673.
The general case remains almost as slow as it was, with the following optimizations:
* The tree is walked one commit less for each ref which contains the commit.
* Git is doing slightly less work as the search is based on parents,  not on children.  As the output is filtered by us anyway, this should be more efficient,  though I didn't measure to be frank.
Additionally,  the git command now respects:
* Filter settings.  The refs that are not visible are not searched, which should eliminate a certain amount of commits for git to chew through.  The impact should not really be worthwhile,  as either most of the time is spent on the references that don't contain the searched commit,  or the searched commit is far enough from …

Show the list of children in the commit details

---

src/Resources/Locales/en_US.axaml

I spotted a few spelling mistakes while using SourceGit. Here are the fixes.
Note: The string keys still have the bad spelling (`"Text.Configure.OpenAI.Prefered"`, `"Text.Configure.OpenAI.Prefered.Tip"`). I left the keys as is – didn't want to touch the code.

Fix spelling mistakes

---

src/ViewModels/CherryPick.cs

Fixes #726.  Looks like a980cc987d60c038e0ce92eee8fb972fb4737ac6 isn't sufficient.  It sorts the commits according to the ordering in history,  but then CherryPick ViewModel reverses the order.
This commit changes CherryPick ViewModel to use string.Join on the commit list without reordering,  so that the ordering is controlled entirely by the caller.

fix: don't reverse commit order when cherry-picking

---

src/Resources/Locales/de_DE.axaml
src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/Views/CommitMessagePresenter.cs

When a commit message happens to contain a commit link and the user elects to right-click it, instead of navigating them to the commit,  present a menu with options to navigate to it or to copy SHA.
I've reused translations for "Copy SHA." "Navigate to" remains untranslated in most locales,  and the English wording choice might be questionable.

feat: context menu for a commit in commit message

---

src/Views/CommitMessagePresenter.cs

When opening the context menu on a SHA in a commit message and using the "Go to" button, SourceGit crashes.
If the lambda to navigate to the SHA is called the `_lastHover` property is null. The `link` variable should be used as it is in the CopySHA logic.

Crash on goto to SHA, NullReferenceException

---

src/Views/CommitBaseInfo.axaml.cs

- When the right click button is pressed it should not navigate to the parent. Navigation actions only should execute with the left button.

[fix] OnSHAPressed avoid right click nav

---

build/resources/rpm/SPECS/build.spec

I discovered that on modern fedora 41 sourcegit rpm package does not install `libicu` dependency, which leads to crash when trying to launch an app:
```
⬢ [user1@toolbx sourcegit]$ sudo dnf install build/sourcegit-0.0.1-1.x86_64.rpm
Updating and loading repositories:
Fedora 41 openh264 (From Cisco) - x86_64                               100% |   2.5 KiB/s |   4.8 KiB |  00m02s
Fedora 41 - x86_64 - Updates                                           100% |   2.0 MiB/s |   6.5 MiB |  00m03s
Fedora 41 - x86_64                                                     100% |   2.5 MiB/s |  35.5 MiB |  00m14s
Repositories loaded.
Package                             Arch      Version                             Repository                Size
Installing:
sourcegit                          x86_64 …
```

Add libicu dependency to RPM spec file

---

.github/workflows/publish-packages.yml
.github/workflows/release.yml
SourceGit.sln

In issue #298 we discussed distributing rpm/deb packages via dedicated repositories. 
Initial idea was to use packagecloud, but since it is now not accessible for new users, buildkite was used as a replacement. Actually, it was quite hard to handle all it's bugs, but now it works!
You can try test packages here:  [rpm](https://buildkite.com/organizations/stone-w4tch3r/packages/registries/sourcegit-fork-test-rpm) and [deb](https://buildkite.com/organizations/stone-w4tch3r/packages/registries/sourcegit-fork-test-deb).
To make it all work, you need: 
- register an organization named **sourcegit** on buildkite
- create two repositories: **sourcegit-deb** and **sorcegit-rpm**
- in personal settings create a token with **write_packages** and **read_packages** scopes
- configure …

Added repositories for deb/rpm packages on buildkite

---

src/Commands/Merge.cs
src/Models/MergeStrategy.cs
src/Resources/Locales/en_US.axaml
src/ViewModels/Histories.cs
src/ViewModels/Merge.cs
src/ViewModels/MergeMultiple.cs
src/ViewModels/Pull.cs
src/ViewModels/Repository.cs
src/Views/BranchTree.axaml.cs
src/Views/MergeMultiple.axaml
src/Views/MergeMultiple.axaml.cs

This PR adds an ability to merge multiple heads.  The operation can be started either from the commit view or from the branch list (second commit).  As such merges often cannot be carried out automatically,  the user is allowed to choose to use "ours" strategy for the merge,  which allows to record a merge and lets user to continue (which would typically include cherry-picking needed commits manually and squashing them into the merge commit).

Merge multiple heads

---

README.md

Adds instructions on how to install DEB & RPM packages by adding the buildkite repos.
Information based on:
- https://buildkite.com/organizations/sourcegit/packages/registries/sourcegit-deb/packages/0193a933-5188-76b6-978c-86ca9300090b
- https://buildkite.com/organizations/sourcegit/packages/registries/sourcegit-rpm/packages/0193a934-0920-779c-92fe-7bd7db5a1ded

Add repository instructions to readme

---

src/Resources/Locales/de_DE.axaml

Added missing keys and changed some instances of "Clone" with 'c' to a more German version with a 'k'. 
Took me a while to figure out what was meant with `InProgress.Merge.Operating` but I think the translation should be good now. 😅

localization: add missing de_DE keys

---

src/Resources/Styles.axaml

This PR changes the text selection brush for the AvaloniaEdit `TextEditor`.
The text selection brush is the `SystemAccentColor`, which is a solid blue on Windows 11 by default. This can reduce the readability of the text when syntax highlighting is enabled.
I suggest to use a semi-transparent brush to improve the readability.

Change text selection brush to improve readability

---

TRANSLATION.md
src/Resources/Locales/ru_RU.axaml

Add missing keys, based on information from the file TRANSLATION.md.
Fix some existing keys, that seem incorrect.

Add/fix Russian translation

---

src/Views/ChangeCollectionView.axaml.cs

The `Space` and `Enter` keys can be used to stage or unstage the selected items in the working copy. The `Space` key works correctly, but the `Enter` key does not.
The `ListBox` in the `ChangeCollectionView` changes the selection when `Enter` is pressed before `WorkingCopy` can stage/unstage the selected items.
Same as for `Space`. The `ChangeCollectionView` should ignore the `Enter` key and not forward the `KeyDown` event to the underlying `ListBox`.

fix: Enter key does not stage/unstage all selected items

---

src/Native/MacOS.cs

On MacOS git can be installed in `/usr/local/` or with HomeBrew.
Add support for these paths.

Support several more variants of git installation on MacOS

---

README.md

I had hard time to get things started as I have not been using this toolchain and nothing was configured.
These commands helped and wanted to share them.
Feel free to change the wording.

Short list of commands needed to get started running locally

---

README.md

- Update APT source configuration to include architecture-specific settings.
Avoid i386 not support warning on debian.

docs: Update README.md with APT source config changes

---

src/Views/Hotkeys.axaml
src/Views/Launcher.axaml
src/Views/Launcher.axaml.cs

Add hotkey Ctrl-Q for exit command on Linux and Windows.
Currently only MacOS supports exit on Cmd-Q.

Exit on Ctrl+Q

---

src/Commands/LFS.cs

Changed the regex to show locks from users with a "." character in their git username.
Before:
After:

Fix: LFS locks does not show if the user name has a dot in it

---

README.md

`%APPDATA%\SourceGit` can be copied to the file browser address bar to open the folder directly.

doc: Update default path for windows

---

src/Commands/Worktree.cs
src/ViewModels/AddWorktree.cs

fix: prevent target branch HEAD from being changed when adding worktree

---

src/Views/DiffView.axaml
src/Views/ImageContainer.cs

- Modified ArrangeOverride methods in ImageView class to independently calculate and apply the aspect ratio based on the instance's image.
Old effect:
New effect:

fix: Ensure each ImageView instance calculates its own aspect ratio

---

src/ViewModels/InProgressContexts.cs
src/ViewModels/Merge.cs
src/ViewModels/WorkingCopy.cs
src/Views/Repository.axaml

check `REBASE_HEAD` file is not safe, and if interactive rebase execute failed, `rebase-merge/stopped-sha` may not exist.
Fixes: #941

fix: Improve in-progress rebase handling

---

src/Commands/Clone.cs
src/Commands/QuerySubmodules.cs
src/ViewModels/Clone.cs
src/ViewModels/UpdateSubmodules.cs

- Remove `--recurse-submodules` flag from the clone command to simplify the cloning process.
- Refactor submodule update logic to handle updating all submodules in a loop and improve progress description handling.
- Attempt to parse submodule list regardless of `submodule status` success.
Fixes #925 & #935

refactor: Update submodules individually to avoid failures (#925)

---

src/Models/Remote.cs
src/Native/Windows.cs

fix: support encoded url in remote

---

src/Commands/Stash.cs
src/Models/RepositorySettings.cs
src/Resources/Locales/en_US.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/ViewModels/StashChanges.cs
src/Views/StashChanges.axaml

feat: Add stash auto-restore functionality (#947)

---

src/Views/CommitMessagePresenter.cs

- Adjust the SHA regex pattern to match commit hashes with a minimum length of 6 characters instead of 10.
The minimum length of a Git commit ID can be 4 hexadecimal characters. Considering that `Diff.cs` uses a 6-40 character string for validation, the check for commit IDs in the commit message has been shortened to 6 characters. For example, GitHub considers a 7-character string as a valid commit ID.

fix: adjust SHA regex pattern to min 6 chars

---

src/ViewModels/LauncherPage.cs
src/ViewModels/Popup.cs
src/ViewModels/Push.cs
src/ViewModels/Repository.cs
src/ViewModels/WorkingCopy.cs
src/Views/WorkingCopy.axaml

Prevent the automatic execution of the push operation when the `NEW` label is visible. This would ensure that users have the opportunity to confirm the creation of a new branch on the remote, rename the branch, or cancel the operation.
Fixes #955

fix: when upstream is null show CommitAndPush and stop auto push (#955)

---

src/Commands/GenerateCommitMessage.cs
src/Models/OpenAI.cs
src/Views/AIAssistant.axaml.cs

I reviewed the code of the official OpenAI SDK, and it seems that the official SDK does not handle the direct return of the Chain-of-Thought `<think>{thinking}</think>\n\n{content}`. After switching to the official SDK, you may need to perform additional processing on the returned results.

fix: Ignore the Chain-of-Thought in AI response

---

src/Views/TextDiffView.axaml.cs

Fixes #966.
Copying from file diff view failed if the selection is created from bottom to top. This causes Selection.StartPosition to be below Selection.EndPosition, so the for loop would not run. Swapping start and end position in these cases fixes the issue.
On a different note, I noticed that any exception thrown in this event handler crashes the application. I think in some cases, such as this, it might be better to catch and log the exception and prompt the user about it.

Fix: Swap selection start and end index if selection is created from bottom to top

---

src/Commands/Worktree.cs
src/Models/Worktree.cs
src/Views/RemoveWorktree.axaml
src/Views/Repository.axaml

Present the worktree name first, then relative path to the main repo.
This is more aligned with Git's own UI,  and works better with UI size constrains.

feat: change worktree presentation

---

src/ViewModels/WorkingCopy.cs

There is one annoying bug I noticed: when you change the unstaged files list in any way - stage single file, stage all, whatever - the number in header does not change. This fix addresses the issue.
I don't particularly like how there is a single call to `OnPropertyChanged` inside the call to `Dispatcher.UIThread.Invoke` as it is not consistent with surrounding code, but it would require further refactoring to fix that, so if it makes sense to improve this fix - please let me know.

fix: Update unstaged filed counter when unstaged files change

---

src/Commands/Command.cs
src/Native/Linux.cs
src/Native/MacOS.cs
src/Native/OS.cs
src/Native/Windows.cs

WIP implementation of command cancellation. Right now it only implements API for safe process termination, further implementation will require some refactoring. 
This will address https://github.com/sourcegit-scm/sourcegit/discussions/753

feat: add safe command termination

---

src/ViewModels/Histories.cs

my workflow often involves creating temporary branches to reorder commits before I push to remotes, and often I use interactive rebase to move *some* commits from one branch to another (much quicker than cherry picking them, especially when there are multiple to move).
however SourceGit has only ever allowed me to use an interactive rebase if the target is inline with my current branch, so I found myself continuously switching to another Git GUI for nothing more than just this step.
turns out this was quite easy to change, it actually took me longer to find the code that handles this than it did to change it... probably since this is the first time I've ever touched a C++ project (JetBrains Rider helped me big time here).
---
for reference, here are some screenshots of the change in …

Improve usability of "interactive rebase"

---

src/SourceGit.csproj

Upgrade Avalonia packages to version 11.2.5 and CommunityToolkit.Mvvm to version 8.4.0 to ensure compatibility and access to the latest features.

Upgrade Avalonia and CommunityToolkit.Mvvm packages

---

src/Views/Launcher.axaml.cs

refactor: Improve key modifier checks and AltGr detection

---

src/ViewModels/Blame.cs
src/Views/Blame.axaml
src/Views/Blame.axaml.cs
src/Views/TextDiffView.axaml.cs

feat: Add commit Tooltip in Blame

---

.github/workflows/build.yml

Although Ubuntu 20.04 is outdated, but Debian 11 is still in LTS, publish with a lower `libc6` version is better.

ci: set linux build container to ubuntu:20.04

---

src/Resources/Locales/es_ES.axaml

+ Add missing spanish translations
+ Update previously translated references of `Patch/patch` as `Parche/parche` to match [git's spanish documentation](https://git-scm.com/docs/git-add/es).
> [!NOTE]
> `Patch/patch` remains only when its a reference to a command or other instances such as a `.patch` file, and not as a noun (`Patch` = `Parche`).
If there is any questions about this change, let me know.

localization: update spanish translations

---

src/ViewModels/Repository.cs

I noticed that a detached HEAD wasn't shown properly. Here is my try to fix it.

fix: Show detached HEAD

---

.github/workflows/package.yml
build/scripts/package.windows.sh

Linux: the newer ubuntu use `zst` instead of `xz` in deb archive, this may reduce the compatibility, so use ubuntu 20.04 with docker container.
Windows: use Compress-Archive in Windows try to prevent Defender false positives

ci: enhance Linux and Windows package workflow

---

src/Commands/Command.cs
src/Commands/ExecuteCustomAction.cs
src/Commands/QueryBranches.cs

fix: Force English locale in branch query command.

---

src/Native/Windows.cs

The DwmExtendFrameIntoClientArea call needs to be posted to the next render frame to ensure the window handle is fully initialized and avoid potential race conditions.
Fixes #1086

fix: schedule DWM frame extension to next render frame on Windows 10

---

src/App.axaml.cs

Fixed the crash when the font is `,SomeFont`.
Situation encountered:
When I added `Noto Color Emoji`, I wrote it at the beginning of the default font. In the TextBox, it was `Noto Color Emoji, HarmonyOS Sans SC`. Then I found that the digital font became emoji, so I deleted the content before `,` and the whole app crashed.

fix: improve font string processing in SetFonts method

---

src/Commands/Branch.cs

Explicitly provided fully qualified reference for the git branch, because there can be a tag and a branch with identical names.
Fixed the push command for branch deletion
Updated the `push` command to use `--delete refs/heads/{name}` instead of `--delete {name}` for clearer branch reference when deleting a remote branch.

Explicitly provided fully qualified reference for the git branch.

---

src/Converters/StringConverters.cs
src/Models/User.cs
src/Views/ChangeCollectionView.axaml
src/Views/DiffView.axaml
src/Views/Histories.axaml
src/Views/RevisionFiles.axaml

enhance: add tooltips to various UI elements for better accessibility

---

src/Models/TextMateHelper.cs
src/Resources/Grammars/jsp.json

- Extend grammar support by allowing multiple file extensions per grammar and adding JSP file type handling.
- Add a new JSON grammar file for JavaServer Pages (JSP) syntax highlighting.

feat: Add JSP grammar support

---

src/Commands/QueryGitCommonDir.cs
src/Models/IRepository.cs
src/Models/Watcher.cs
src/Resources/Locales/de_DE.axaml
src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/it_IT.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/ViewModels/Launcher.cs
src/ViewModels/Repository.cs

run `git rev-parse --git-dir --git-common-dir` can get both paths, but I don't have good idea to read these

refactor: use $GIT_COMMON_DIR instead of cut $GIT_DIR/worktrees

---

src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/it_IT.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/ViewModels/RepositoryConfigure.cs
src/Views/RepositoryConfigure.axaml

Minor changes that adds Azure DevOps workitems to the available templates of the issue trackers.
The template needs to be populated with the organization and the workspace. The template URL is `https://dev.azure.com/yourcompany/workspace/_workitems/edit/[CODE]`
Added localization for the new command in en, es, fr, it, pt and ru languages.

Adding template for Azure DevOps workitems

---

src/ViewModels/WorkingCopy.cs
src/Views/WorkingCopy.axaml

Implements #1155.
Adds a searchfilter-box, identical to the one in the Unstaged area.
Also adds a RaiseException if committing with a Staged-filter active, since otherwise more changes than the visible ones could be committed. NOTE: This could be made into a warning-dialog with options "Continue? Yes / No", similar to `ConfirmCommitWithoutFiles()`.

Add filterbox in Staged area, same as in Unstaged area

---

src/Commands/MergeTool.cs
src/Models/Change.cs
src/Resources/Locales/en_US.axaml
src/ViewModels/WorkingCopy.cs
src/Views/ChangeStatusIcon.cs
src/Views/Conflict.axaml
src/Views/WorkingCopy.axaml

Implements #1168.
Adds a new icon-button (reusing the `Icons.Conflict` image) on the UNSTAGED toolbar (in LOCAL CHANGES view). This new button is visible only when `HasUnsolvedConflicts` and has a tooltip text of "OPEN ALL CONFLICTS IN EXTERNAL MERGETOOL".
When pressed, this button calls `UseExternalMergeTool()` with a null argument, which is passed on to `Commands.MergeTool.OpenForMerge()` and will cause the <file> argument for the `git mergetool` command to be left out. This causes Git to run the specified merge tool on ALL conflicted files in the workspace (one after another), rather than on just a single file. (The sequence will be terminated prematurely if the merge tool exits one of the files without having saved a resolved version.)
This PR also makes a few non-translated strings …

Add button for running external mergetool on ALL conflicts

---

src/Commands/QueryBranches.cs
src/Models/Branch.cs
src/ViewModels/BranchTreeNode.cs
src/ViewModels/FastForwardWithoutCheckout.cs
src/ViewModels/Fetch.cs
src/ViewModels/FetchInto.cs
src/ViewModels/Merge.cs
src/ViewModels/Pull.cs
src/ViewModels/Repository.cs

enhance: navigate to upstream head after fetch, pull, and merge

---

src/Commands/Statistics.cs

Convert the string's AsSpan to ReadOnlaySpan, and use Span's Slice instead of SubString to reduce temporary strings and memory allocation

minimize temporary strings for better performance

---

src/Models/ExternalMerger.cs

Meld is now supported on windows:
`winget install Meld.Meld`
Command copied from the Linux usage below.
First time PR'er here so please let me know if you need anything else.

Add Meld as an option for External Merge Tool for the windows platform.

---

src/Resources/Locales/en_US.axaml
src/ViewModels/Launcher.cs
src/Views/Hotkeys.axaml
src/Views/Launcher.axaml
src/Views/Launcher.axaml.cs

- added Alt+Space for opening Workspaces context menu (which can then be navigated normally with arrows)
- added Alt+1 through Alt+9 for switching to corresponding workspace
This references #1267

Added workspaces shortcuts

---

src/Models/RepositorySettings.cs

When using `Amend`, `CommitMessages` may store duplicate commit messages.

fix: Trim and normalize commit message history line endings

---

src/Models/Watcher.cs

Fixes #1344.
Added a few more patterns in `Watcher.OnRepositoryChanged()` and `Watcher.OnWorkingCopyChanged()` :
* Skip files frequently updated by Git `fsmonitor--daemon` and Visual Studio, to ease debugging and for early exit. 
* Skip `.git` file under submodule directories, for consistency.
* Check also for `ORIG_HEAD` under `.git/modules/<submodule>/`, to improve handling of submodules.
* Check for `MERGE_HEAD` and `AUTO_MERGE` under `.git/`, to improve handling of submodules (etc) during merging.
NOTE: Maybe the `MERGE_HEAD` and/or `AUTO_MERGE` files should affect some other update-timers as well, if needed to improve refresh during Merging? (Currently only affecting `_updateSubmodules` and `_updateWC`.)

Add more FileSystemWatcher patterns, to improve refresh of submodules

---

src/Views/ChangeStatusIcon.cs

This makes code more consistent and gives better overview of all the icons.
(Potentially, this special/outlier icon could be moved into the existing arrays as an extra `ChangeState` enum-value.)

Refactoring: Move hardcoded brush/strings (for Conflict-icon) into named constants

---

src/ViewModels/Conflict.cs

Improved IsConflicResolved check, to work correctly for submodule conflicts.
~~Added an extra (lock-free) call to git-status with `--porcelain=v2` which makes it easy to check that:~~
* ~~The file is still "unmerged".~~
* ~~The file is a submodule (or not).~~
If the file is a submodule, we always ~~return `false` (while it's unmerged)~~ regard the conflict as unresolved (while Unstaged), since we can't use text-diff check on submodules and the conflict is not resolved until it's Staged.

Fix IsConflictResolved check for submodule

---

src/Commands/IsBinary.cs
src/Models/Commit.cs
src/Models/DiffOption.cs
src/ViewModels/CommitDetail.cs
src/ViewModels/StashesPage.cs
src/ViewModels/WorkingCopy.cs

Reduces redundant occurrences of this "magic number" to a single location.

Refactoring: Add new constant Models.Commit.EmptyTreeSHA1

---

src/ViewModels/WorkingCopy.cs

Unmerged files (i.e unresolved conflicts) should only appear in the Unstaged area, and not "duplicated" in the Staged area.
Motivation:
* The user-friendly git-status command does not show these as "Changes to be committed".
* If they appear in the Staged area, they are quite redundant since the Diff view will just show "No changes or only EOL changes".
* Some other Git UIs (like Fork) don't show these as Staged items either.
NOTE: According to the docs for git-status "Short Format" and `--porcelain` format(s), the `<XY>` field values for _**unmerged paths**_ (specifically) do NOT actually represent the Index & Working-tree states, INSTEAD they represent the states introduced by each HEAD in the merge (i.e Theirs & Ours, relative to Base).

Don't show Unmerged files in Staged area

---

src/Models/ImageDecoder.cs
src/SourceGit.csproj
src/ViewModels/ImageSource.cs

Added support for displaying DDS images using the Pfim library.

[Feature] DDS image support

---

src/Models/Commit.cs
src/Models/InlineElementCollector.cs
src/Models/IssueTrackerRule.cs
src/ViewModels/CommitDetail.cs
src/Views/CommitMessagePresenter.cs
src/Views/CommitSubjectPresenter.cs

Instead of checking intersections of inline elements yourself before adding an inline element, the new class `InlineElementCollector` prevents intersections internally.
Additionally the inline elements are sorted by the new class, so it's no longer necessary to do this after adding the inline elements.

refactor: collecting inlines for subjects

---

src/Views/CommitSubjectPresenter.cs

Some teams use issue tracker numbers in front of the commit message subject, followed by a colon.  It was not possible to use an issue tracker rule in such cases, since the issue tracker number would be interpreted as a keyword due to the colon and therefore displayed in bold face instead of as a link into the issue tracker.

fix: issue tracker rule over keyword in subject

---

src/ViewModels/Blame.cs
src/Views/Blame.axaml
src/Views/Blame.axaml.cs

This PR aims to update the blame window with the commit you click on in the left column.
It also adds a history so you can go back and forward through commits with clickable buttons and Mouse4/5 for back and forward.

[Feature] Update blame window when clicking/navigating commits

---

src/Models/NumericSort.cs

* Refactor the 2 do-loops into simpler while-loops and replace the use of "tmp1/2" char-arrays with calls to String.Substring().
* Rename the "loc1/2" variables to "subLen1/2", for clarity, since they represent the lengths of the two extracted Substrings.
These changes make the logic more compact and easier to follow.
Loosely related to issues #597, #1413 and PR #1401 (where an earlier try at this refacoring was included but not merged).

Refactor: reduce redundant code in NumericSort.Compare()

---

src/ViewModels/WorkingCopy.cs

There's no need to populate a `Dictionary` just to diff the `old` and `cur` Lists of Changes (in the equal list-length case).
If there has been no changes in the working-copy between the two calls to `QueryLocalChanges`, we can assume that the items in the two lists are reported (by `git-status`) in equal sort-order. And consequently, if the `Path` value DOES differ between two items at equal index in the two equal-length lists, we can directly conclude that some change has occurred between these two calls.
Thus, we only need to loop through the successive list-indices (of the two equal-length lists), comparing the `Path`, `Index` and `WorkTree` values of the `o` and `c` items at each such index.
Loosely related to PR #1401 (where this refacoring was included but not merged).

Refactor: Optimize the WorkingCopy.IsChanged() method

---

src/Views/ChangeStatusIcon.cs

Just a minor one, but I feel that the change status icons are a bit too bright when in dark mode.
This PR refactors the brushes in `ChangeStatusIcon` and dynamically darkens or lightens the gradient color depending on what theme is set. It also listens for theme changes so it can re-render if the user switches.
It's pretty subtle right now but a good starting point for theme-aware icon colors.

Dark theme change status icons

---

src/Commands/QueryStashes.cs
src/Resources/Locales/en_US.axaml
src/ViewModels/StashesPage.cs

This is a follow-up PR for #1426, adding the only missing piece for being able to re-use the Message from a Stash (by copying it to Clipboard). Also, it refactors the query-code from commit 6d682ac.
* Refactor: Simplify parsing in QueryStashes, by passing the `-z` argument to `git stash list` for item separation.
* Add "Copy Message" command in stash-item context-menu.

Add "Copy Message" to context-menu for Stash item

---

src/Views/AddWorktree.axaml.cs

Fix the error of adding an extra slash when selecting a working tree directory.

fix: fix working tree folder path detection error

---

src/Resources/Locales/de_DE.axaml

It's translation time again.  ;-)
@love-linger You changed the translation of key `Text.Configure.CustomAction.Arguments.Tip` to reflect the selected tag as additional possibility for an argument.  Since this key was only modified and not new, it was not mentioned in "TRANSLATION.md".  It would be nice if such keys could be tagged automatically in any way, so that the translation can be checked and maybe adapted.  If you know of a way to accomplish this, it would be nice.

localization: update German translations

---

src/Commands/QuerySingleCommit.cs

Searching for a tree or blob hash instead of a commit hash created a seemingly never-ending search (internally an exception was thrown).
Examples for non-ending searches in the SourceGit repository itself are searching for 6b83a0a (that is the tree "src" of commit 190d2ee) or e686a53 (that is the file ".gitignore" in the tree of commit 190d2ee).

fix: searching for tree/blob hash never-ending

---

src/Views/ExecuteCustomAction.axaml
src/Views/ExecuteCustomAction.axaml.cs

This PR aims to improve keyboard usability and streamline interactions:
1. For keyboard users, selecting and typing previously required an extra click on the input field. With this change, users can start typing immediately after the UI is shown.
2. It allows seamless navigation between input fields using the Tab key.
- Added an `OnLoaded` event to automatically focus the first focusable input (either a `TextBox` or `CheckBox`) when the view is loaded.
- Removed `IsTabStop` from `SelectableTextBlock`. It can still be manually selected with a double click if needed.
- Replaced `ListBox` with `ItemsControl` to properly handle focus and tab navigation for editable controls.

enhance: enable focus for custom action edit controls

---

src/Views/Preferences.axaml.cs

https://github.com/sourcegit-scm/sourcegit/issues/1483

fix: Custom Shell/Terminal or Diff/Merge Tool crash fix

---

src/Commands/Command.cs
src/Commands/Discard.cs
src/Commands/GenerateCommitMessage.cs
src/Commands/GitFlow.cs
src/Commands/MergeTool.cs
src/Commands/QueryLocalChanges.cs
src/Commands/SaveChangesAsPatch.cs
src/Commands/SaveRevisionFile.cs
src/Commands/UnstageChangesForAmend.cs
src/ViewModels/ExecuteCustomAction.cs
src/ViewModels/Launcher.cs
src/ViewModels/RevisionCompare.cs

As part of my work on #1439 I'd like to remove any UI concerns from the `SourceGit.Commands` namespace.
I'm no Avalonia expert but it seems simple enough to detect the wrong thread in `Launcher` when processing notifications and dispatch to the UI thread as needed.
The only outstanding question is whether to use `UIThread.Post` or `UIThread.Invoke` as the existing code used a mixture of both.

refactor: auto dispatch notifications to UI thread in `Launcher`

---

src/Models/MergeMode.cs
src/ViewModels/Merge.cs

This adds another configuration possibility for the default merge mode to the already existing per branch git configuration `branch.<name>.mergeoptions` (#540) and the per repo preference "Preferred Merge Mode" (#1156).
Defined values:
- `false`: do no fast-forward merge
- `only`: do only a fast-forward merge
This is configurable by for example `git config set --global merge.ff <value>` for a global (meaning the current user) configuration.
The priority between these configurations/preferences is:
- git configuration `branch.<name>.mergeoptions` (#540)
- git configuration `merge.ff`
- preference "Preferred Merge Mode" (#1156)

enhance: respect git config `merge.ff`

---

src/ViewModels/CreateBranch.cs
src/ViewModels/RenameBranch.cs

Switch the `Split` + `Join` pattern to `Regex`, which is faster and avoids allocating a temporary array.

enhance: use regex to fix branch names

---

src/Resources/Locales/de_DE.axaml

Changes:
- "Integrationen" is more common and modern than "Einbindungen"
- Replaced the word "Graph" with "Verlauf" because for the users it is quite synonymous
- Aligned issue tracker samples wording
- Use the more direct translation "System-Prompt" as it is a recognized term in German developer slang
- Aligned the use of words if similar words are used already or the context uses another word for the same thing
- Some grammar fixes
Fixes #1523

German Translation Maintenance

---

src/Resources/Locales/en_US.axaml

The word "Histories" wouldn't ordinarily be used in this context.

ux: replace "histories" with "history"

---

src/ViewModels/Histories.cs
src/ViewModels/WorkingCopy.cs

Added some missing keyboard shortcut hints in a couple of menus. There are probably more missing but these are the ones I noticed.
I went with `Key.Enter` and `Key.Delete` in the (un)stash menus. `Key.Space` and `Key.Back` are also supported but I don't see any way to show two key hints on a single menu item.

ux: show a few more shortcuts on menu items

---

src/App.axaml.cs
src/Commands/Blame.cs
src/Commands/Config.cs
src/Commands/Diff.cs
src/Commands/QueryBranches.cs
src/Commands/QueryRevisionObjects.cs
src/Commands/Statistics.cs
src/Models/Change.cs
src/Models/OpenAI.cs
src/Models/Stash.cs
src/Models/Statistics.cs
src/Models/User.cs
src/ViewModels/BranchTreeNode.cs
src/ViewModels/ChangeTreeNode.cs
src/ViewModels/CommitDetail.cs
src/ViewModels/FileHistories.cs
src/ViewModels/InteractiveRebase.cs
src/ViewModels/PushRevision.cs
src/ViewModels/SubmoduleCollection.cs
src/ViewModels/TagCollection.cs
src/ViewModels/WorkingCopy.cs
src/Views/CommitMessageEditor.axaml.cs
src/Views/CommitMessageTextBox.axaml.cs

Refactor various string operations for efficiency and readability.
- Use `StringReader.ReadLine` instead of manually searching for `\n` in a loop
- Don't specify `StringComparison.Ordinal` when working with `char` (ordinal is the default)
- Use `string.Split(sep, 2)` instead of `IndexOf` + `Substring` + `Substring`
- Use `AsSpan` over `Substring` where possible

refactor: streamline certain string operations

---

src/Resources/Locales/de_DE.axaml
src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/it_IT.axaml
src/Resources/Locales/ja_JP.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/Resources/Locales/ta_IN.axaml
src/Resources/Locales/uk_UA.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml

Stumbled on an unused text resource, so I wrote the following bash+ripgrep command to find all 12.
```
rg 'Key="Text\.([^"]+)"' -Nor '$1' ./src/Resources/Locales/en_US.axaml \
| xargs -I {} bash -c 'if ! rg -qFw --glob "!src/Resources/Locales/**" "{}"; then echo "{}"; fi'
```

refactor: remove unused text resources

---

src/ViewModels/BranchCompare.cs
src/ViewModels/CommitDetail.cs
src/ViewModels/RevisionCompare.cs
src/ViewModels/StashesPage.cs
src/ViewModels/WorkingCopy.cs

I didn't realize there was a hotkey for launching the external merger. Added menu item tags to make this discoverable.

ux: hotkey tag on external merger menu items

---

src/Resources/Locales/en_US.axaml
src/Views/Askpass.axaml
src/Views/CommitBaseInfo.axaml
src/Views/CommitMessageEditor.axaml
src/Views/ConfirmRestart.axaml
src/Views/ImageDiffView.axaml
src/Views/InteractiveRebase.axaml.cs
src/Views/Push.axaml
src/Views/RepositoryConfigure.axaml

Found 22 static strings that weren't localizable. I took a guess at the key names, feel free to rename.

localization: move strings into resources

---

src/Commands/Rebase.cs
src/Resources/Locales/de_DE.axaml
src/Resources/Locales/en_US.axaml
src/Resources/Locales/es_ES.axaml
src/Resources/Locales/fr_FR.axaml
src/Resources/Locales/it_IT.axaml
src/Resources/Locales/ja_JP.axaml
src/Resources/Locales/pt_BR.axaml
src/Resources/Locales/ru_RU.axaml
src/Resources/Locales/ta_IN.axaml
src/Resources/Locales/uk_UA.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/ViewModels/Histories.cs
src/ViewModels/InteractiveRebase.cs
src/Views/InteractiveRebase.axaml

I often have minor patches in my workspace that I'd like to keep during interactive rebase. This PR adds the same autostash ability already available in non-interactive rebase.
It would also be nice to allow commit rename with pending changes so long as nothing is staged, however I couldn't find an easy way to determine this from the `Histories` view model.

enhance: support `--autostash` on interactive rebase

---

src/Resources/Locales/en_US.axaml
src/ViewModels/RepositoryConfigure.cs
src/Views/RepositoryConfigure.axaml

- git hash id length is 40
- gerrit change-id  length is 41, and must startwith "I"

add gerrit change-id rule

---

src/ViewModels/Repository.cs

Fixes worktree detection in submodules where worktree.FullPath differs from commonDir path.

fix: exclude main worktree by comparing with commonDir in submodules

---

src/Resources/Locales/en_US.axaml
src/Resources/Locales/zh_CN.axaml
src/Resources/Locales/zh_TW.axaml
src/Views/Histories.axaml.cs

fix: the menu of copy tag name in history view

---

src/Models/Remote.cs

Fix https://github.com/sourcegit-scm/sourcegit/issues/1689

fix: Fixed regex for repository url to allow the 'dot' symbol

---

src/Resources/Locales/ru_RU.axaml

This is update of Russian translation. Below the explanation for Russian speakers. They is useless for non-speakers, because they are unlikely to understand nuances. Below the explanations of some changes on Russian.

Update Russian translation - Welcome Page and top-level menus

---

src/Resources/Locales/en_US.axaml
src/ViewModels/WorkingCopy.cs
src/Views/CommitMessageTextBox.axaml.cs

- Added ClearCommitMessageHistory method to WorkingCopy ViewModel with user confirmation
- Added "Clear History" menu item to commit message picker dropdown
- Implemented thread-safe collection clearing using Dispatcher.UIThread.Invoke
- Added localization support for clear history button and confirmation dialog
- Follows existing codebase patterns for destructive operations with async/await

feat: add clear history button to commit message template/history dropdown

---

src/Resources/Locales/es_ES.axaml

- Add missing strings
Hi @love-linger , I need more context about the `Text.Preferences.AI.ReadApiKeyFromEnv` string. If I understand correctly, there is an API key located in ENV and you need to input that variable name to load it's value?
If this is correct, I going to adapt the spanish version a little bit because the literal translation is confusing with the phrasing in spanish.

localization: update Spanish translation

---

src/Native/Windows.cs

The current code uses incorrect parameters when checking for Windows versions below Windows 10. The correct threshold should be (10, 0, 22000).

fix: correct Windows version parameter in window frame fix
